"""auto update

Revision ID: b7afcc920cff
Revises: 
Create Date: 2026-08-25 14:10:58.881108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7afcc920cff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('terminal_id', sa.String(), nullable=True),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('auth_mode', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_terminal_id'), 'access_logs', ['terminal_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_no', sa.String(), nullable=True),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('emp_no', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('requester_emp_no', sa.String(), nullable=True),
    sa.Column('requester_name', sa.String(), nullable=True),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('hr_approver', sa.String(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hr_comment', sa.String(), nullable=True),
    sa.Column('manager_approver', sa.String(), nullable=True),
    sa.Column('manager_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('manager_comment', sa.String(), nullable=True),
    sa.Column('ceo_approver', sa.String(), nullable=True),
    sa.Column('ceo_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ceo_comment', sa.String(), nullable=True),
    sa.Column('rejected_by', sa.String(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_id'), 'approvals', ['id'], unique=False)
    op.create_table('attendance_reasons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pay_effect', sa.String(), nullable=True),
    sa.Column('deduct_rate', sa.Float(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('offsettable', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_reasons_id'), 'attendance_reasons', ['id'], unique=False)
    op.create_table('daily_attendances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=True),
    sa.Column('raw_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_count', sa.Integer(), nullable=True),
    sa.Column('scheduled_minutes', sa.Integer(), nullable=True),
    sa.Column('work_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('night_minutes', sa.Integer(), nullable=True),
    sa.Column('holiday_minutes', sa.Integer(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('early_leave_minutes', sa.Integer(), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('reason_note', sa.String(), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=True),
    sa.Column('adjusted_by', sa.String(), nullable=True),
    sa.Column('adjust_history', sa.String(), nullable=True),
    sa.Column('confirm_status', sa.String(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('leave_request_id', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_attendances_approval_id'), 'daily_attendances', ['approval_id'], unique=False)
    op.create_index(op.f('ix_daily_attendances_id'), 'daily_attendances', ['id'], unique=False)
    op.create_index(op.f('ix_daily_attendances_leave_request_id'), 'daily_attendances', ['leave_request_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('pay_type', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('monthly_salary', sa.Float(), nullable=True),
    sa.Column('pay_cycle', sa.String(), nullable=True),
    sa.Column('std_start', sa.String(), nullable=True),
    sa.Column('std_end', sa.String(), nullable=True),
    sa.Column('break_minutes', sa.Integer(), nullable=True),
    sa.Column('grace_minutes', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('annual_leave_days', sa.Float(), nullable=True),
    sa.Column('terminal_user_id', sa.String(), nullable=True),
    sa.Column('manager_emp_no', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    op.create_index(op.f('ix_employees_terminal_user_id'), 'employees', ['terminal_user_id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('granted_days', sa.Float(), nullable=True),
    sa.Column('used_days', sa.Float(), nullable=True),
    sa.Column('pending_days', sa.Float(), nullable=True),
    sa.Column('converted_days', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_employees_terminal_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_daily_attendances_leave_request_id'), table_name='daily_attendances')
    op.drop_index(op.f('ix_daily_attendances_id'), table_name='daily_attendances')
    op.drop_index(op.f('ix_daily_attendances_approval_id'), table_name='daily_attendances')
    op.drop_table('daily_attendances')
    op.drop_index(op.f('ix_attendance_reasons_id'), table_name='attendance_reasons')
    op.drop_table('attendance_reasons')
    op.drop_index(op.f('ix_approvals_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_access_logs_terminal_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###