"""auto update

Revision ID: f0c5bb3d23d4
Revises: b7afcc920cff
Create Date: 2026-08-25 14:11:20.880070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c5bb3d23d4'
down_revision: Union[str, Sequence[str], None] = 'b7afcc920cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Float(), nullable=True),
    sa.Column('half_day_type', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('reflected', sa.Boolean(), nullable=True),
    sa.Column('reflected_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_approval_id'), 'leave_requests', ['approval_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_table('overtime_banks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('target_leave_days', sa.Float(), nullable=True),
    sa.Column('target_attendance_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_banks_approval_id'), 'overtime_banks', ['approval_id'], unique=False)
    op.create_index(op.f('ix_overtime_banks_id'), 'overtime_banks', ['id'], unique=False)
    op.create_index(op.f('ix_overtime_banks_target_attendance_id'), 'overtime_banks', ['target_attendance_id'], unique=False)
    op.create_table('payroll_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=True),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('pay_cycle', sa.String(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('regular_minutes', sa.Integer(), nullable=True),
    sa.Column('overtime_minutes', sa.Integer(), nullable=True),
    sa.Column('holiday_minutes', sa.Integer(), nullable=True),
    sa.Column('night_minutes', sa.Integer(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('offset_minutes', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Float(), nullable=True),
    sa.Column('leave_days', sa.Float(), nullable=True),
    sa.Column('work_days', sa.Integer(), nullable=True),
    sa.Column('confirmed_days', sa.Integer(), nullable=True),
    sa.Column('base_pay', sa.Float(), nullable=True),
    sa.Column('overtime_pay', sa.Float(), nullable=True),
    sa.Column('holiday_pay', sa.Float(), nullable=True),
    sa.Column('night_pay', sa.Float(), nullable=True),
    sa.Column('late_deduction', sa.Float(), nullable=True),
    sa.Column('offset_credit', sa.Float(), nullable=True),
    sa.Column('absent_deduction', sa.Float(), nullable=True),
    sa.Column('gross_pay', sa.Float(), nullable=True),
    sa.Column('net_pay', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_items_id'), 'payroll_items', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_items_payroll_run_id'), 'payroll_items', ['payroll_run_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('pay_cycle', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('confirmed_only', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_table('weekend_work_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emp_no', sa.String(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=True),
    sa.Column('planned_start', sa.String(), nullable=True),
    sa.Column('planned_end', sa.String(), nullable=True),
    sa.Column('planned_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('premium_rate', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('approval_id', sa.Integer(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekend_work_requests_approval_id'), 'weekend_work_requests', ['approval_id'], unique=False)
    op.create_index(op.f('ix_weekend_work_requests_id'), 'weekend_work_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekend_work_requests_id'), table_name='weekend_work_requests')
    op.drop_index(op.f('ix_weekend_work_requests_approval_id'), table_name='weekend_work_requests')
    op.drop_table('weekend_work_requests')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_payroll_items_payroll_run_id'), table_name='payroll_items')
    op.drop_index(op.f('ix_payroll_items_id'), table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index(op.f('ix_overtime_banks_target_attendance_id'), table_name='overtime_banks')
    op.drop_index(op.f('ix_overtime_banks_id'), table_name='overtime_banks')
    op.drop_index(op.f('ix_overtime_banks_approval_id'), table_name='overtime_banks')
    op.drop_table('overtime_banks')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_approval_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###